import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";

import { Roboto_Mono } from 'next/font/google';
const robotoMono = Roboto_Mono({ subsets: ['latin' ]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoMono.className} style={{backgroundColor:"#262626"}}>
        <div className="d-inline-flex">
          <h2 className="pt-2 ps-3" style={{color:"white"}}>Johnathan Stowers</h2> 
          <h5 className="pt-3 ps-2" style={{color:"#d9d9d9"}}> - Full Stack Developer, Aspiring Software Engineer </h5>
        </div>
        <div></div>
        <p2 className="pt-0 ps-3" style={{color:"#d9d9d9"}}> Macon, Georgia - J.Stowers1@icloud.com - (210) 827-5077 </p2>
        
        <div className="p-4" style={{minWidth: "0.2vw"}}>
          {children}
        </div>
      </body>
    </html>
  );
}
